version: '2'

services:
  zookeeper1:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always

  kafka1:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "wordcollector1:1:1"
    depends_on:
      - zookeeper1
    restart: always

  mydb:
    image: mysql
    container_name: mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: localspringbootdb
    ports:
      - "3306:3306"

  python_producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:9092
      - KAFKA_TOPIC=wordcollector1
    depends_on:
      - kafka1
    restart: always
    

  java_consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:9092
      - MYSQL_HOST=mydb
      - MYSQL_PASSWORD=12345
      - MYSQL_PORT=3306
      - MYSQL_DB_NAME=localspringbootdb
      - MYSQL_USER=root
    depends_on:
      - python_producer
      - mydb
    restart: always

